#!/bin/sh

server() {
    if test $API_PORT ; then 
        python3 -c "import asyncio;asyncio.run(asyncio.create_subprocess_shell('python3 server.py'))"
        echo "Started API..."
    else
        echo "Skipping API..."
    fi
}

server
python3 -m venom
